[package]
name = "kcl"
version = "0.1.0"
edition = "2021"
authors = ["Ivan De Marino <detronizator@gmail.com>", "Kafkesc <https://github.com/kafkesc>"]
repository = "https://github.com/kafkesc/ksunami"
homepage = "https://github.com/kafkesc/ksunami"
description = "TODO"
license = "MIT OR Apache-2.0"
keywords = ["kafka", "consume", "lag", "monitoring", "performance"]
categories = ["TODO"]
exclude = [
    ".github/",
    ".gitignore",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
clap = { version = "4.3.0", features = ["derive", "deprecated", "env", "wrap_help"] }
ctrlc = { version = "3.3.1", features = ["termination"] }
env_logger = "0.10.0"
konsumer_offsets = { version = "0.2.0", default-features = false, features = ["ts_chrono"] }
log = "0.4.17"
regex = "1.8.2"
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = ["rt", "rt-multi-thread", "time", "sync", "macros"] }

[target.'cfg(unix)'.dependencies]
rdkafka = { version = "0.31.0", features = ["ssl-vendored", "gssapi-vendored", "libz-static"] }

[profile.release]
strip = true # Automatically strip symbols from the binary.
lto = true   # Link time optimization - see https://llvm.org/docs/LinkTimeOptimization.html.
