[package]
name = "kcl"
version = "0.1.0"
edition = "2021"
authors = ["Ivan De Marino <detronizator@gmail.com>", "Kafkesc <https://github.com/kafkesc>"]
repository = "https://github.com/kafkesc/ksunami"
homepage = "https://github.com/kafkesc/ksunami"
description = "TODO"
license = "MIT OR Apache-2.0"
keywords = ["kafka", "consume", "lag", "monitoring", "performance"]
categories = ["TODO"]
exclude = [
    ".github/",
    ".gitignore",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.71"
axum = { version = "0.6.18", features = ["http2"] }
chrono = "0.4.26"
clap = { version = "4.3.11", features = ["derive", "deprecated", "env", "wrap_help"] }
const_format = "0.2.31"
ctrlc = { version = "3.4.0", features = ["termination"] }
env_logger = "0.10.0"
exit-code = "1.0.0"
hyper = { version = "0.14.27", features = ["http1", "http2", "server", "runtime", "tcp"] }
konsumer_offsets = { version = "0.3.0", default-features = false, features = ["ts_chrono"] }
log = "0.4.19"
regex = "1.9.1"
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["rt", "rt-multi-thread", "time", "sync", "macros"] }
tokio-util = "0.7.8"

[target.'cfg(unix)'.dependencies]
rdkafka = { version = "0.33.2", features = ["ssl-vendored", "gssapi-vendored", "libz-static"] }

[profile.release]
strip = true # Automatically strip symbols from the binary.
lto = true   # Link time optimization - see https://llvm.org/docs/LinkTimeOptimization.html.
